### ISSUE TITLE
0.39 vot index

### ISSUE THREAD

**Issue by LinYark** [Zhangyong-Tang/DFAT#2]
I download the code from the official website of VOT and use the official Python toolkit of VOT. 

The result of votrgbtir2020 is only 0.347. 

There is a certain gap with the report of 0.39. 

Does this code correspond to the index of 0.39 in the report?

thanks

**Comment by LinYark** [comment]
it can be achieved to 0.39. Same env, up to 0.39 ,down to 0.34.
The Vot-result is unstable. 
3 months ago this problem has been closed. But I forgot to close this issue. sorry for that.

**Comment by Zhangyong-Tang** [comment]
I am sorry to reopen this issue. 
Actually, the version before 0.2.0 or the newest version of vot-python-toolkit is stable.
But the result is still not 0.39, so i think the result(0.39) is not the direct output of a certain version of toolkit.
(Use version 0.2.0, result higher than 0.39 should be obtained)
