### ISSUE TITLE
您好, 关于决策融合的策略

### ISSUE THREAD

**Issue by NewboySoCool** [Zhangyong-Tang/DFAT#4]
作者您好！首先感谢您出色的工作！
我想问下决策融合的实现
w = self.data_mean(self._convert_score(cls_rgb), self._convert_score(cls_ir))
cls = scale * (w[1] * cls_ir + w[0] * cls_rgb) / ((w[1] + w[0]))
loc = (0.5 * loc_ir + 0.5 * loc_rgb)
然后对cls、loc再做后处理得到最后的结果。 
 𝜆12 and 𝜆22 are the learned weights，代码中通过这个self.data_mean来实现嘛？ 

这个融合的机制可以用到其他的Siamese跟踪器上吗？
或者关于这种 针对Siamese跟踪器进行响应图融合，然后再做后处理的决策级融合的方法有推荐的嘛？
期待您的回复！

**Comment by Zhangyong-Tang** [comment]
您好，感谢您对DFAT的关注。

两个参数应该就是通过self.data_mean()获取的。

这个融合机制应该是可以用到其他siamese跟踪器上的。

目前像这种在线自适应的目前可能没有，离线自适应的您可以关注一下HMFT：https://arxiv.org/pdf/2204.04120，TAAT：https://arxiv.org/abs/2201.08949，以及MELT：https://dl.acm.org/doi/abs/10.1145/3678176。

**Comment by NewboySoCool** [comment]
> 您好，感谢您对DFAT的关注。
> 
> 两个参数应该就是通过self.data_mean()获取的。
> 
> 这个融合机制应该是可以用到其他siamese跟踪器上的。
> 
> 目前像这种在线自适应的目前可能没有，离线自适应的您可以关注一下HMFT：[https://arxiv.org/pdf/2204.04120，TAAT：https://arxiv.org/abs/2201.08949，以及MELT：https://dl.acm.org/doi/abs/10.1145/3678176。](https://arxiv.org/pdf/2204.04120%EF%BC%8CTAAT%EF%BC%9Ahttps://arxiv.org/abs/2201.08949%EF%BC%8C%E4%BB%A5%E5%8F%8AMELT%EF%BC%9Ahttps://dl.acm.org/doi/abs/10.1145/3678176%E3%80%82)

感谢您的回复！

**Comment by NewboySoCool** [comment]
> 您好，感谢您对DFAT的关注。
> 
> 两个参数应该就是通过self.data_mean()获取的。
> 
> 这个融合机制应该是可以用到其他siamese跟踪器上的。
> 
> 目前像这种在线自适应的目前可能没有，离线自适应的您可以关注一下HMFT：[https://arxiv.org/pdf/2204.04120，TAAT：https://arxiv.org/abs/2201.08949，以及MELT：https://dl.acm.org/doi/abs/10.1145/3678176。](https://arxiv.org/pdf/2204.04120%EF%BC%8CTAAT%EF%BC%9Ahttps://arxiv.org/abs/2201.08949%EF%BC%8C%E4%BB%A5%E5%8F%8AMELT%EF%BC%9Ahttps://dl.acm.org/doi/abs/10.1145/3678176%E3%80%82)

同时想请教下另一个问题，现在我有个Siamese的跟踪网络，但是针对单个模态的。我现在想要对RGB-T 两路分别进行跟踪后，对cls、loc的输出响应图部分做融合。我直接尝试了您的决策融合的方法，但效果不佳，您的方法是不是得在训练阶段就使用到RGB-T的数据以及相对应的损失函数才能发挥作用？

**Comment by Zhangyong-Tang** [comment]
DFAT在训练阶段是没有用到rgbt数据的，也正是因为这样，才会出现在决策端有偏向性的数据结果。
您可以观察您在决策端是否存在有偏向的情况，如不存在则这个算法有效性受限，您可以尝试根据分类相应图最高值来计算融合比例。

**Comment by NewboySoCool** [comment]
> DFAT在训练阶段是没有用到rgbt数据的，也正是因为这样，才会出现在决策端有偏向性的数据结果。 您可以观察您在决策端是否存在有偏向的情况，如不存在则这个算法有效性受限，您可以尝试根据分类相应图最高值来计算融合比例。

好的，感谢回复！ 正在拜读您的另一篇论文MELT，我尽可能地多去尝试。再次感谢您和您团队出色的工作！

**Comment by NewboySoCool** [comment]
> DFAT在训练阶段是没有用到rgbt数据的，也正是因为这样，才会出现在决策端有偏向性的数据结果。 您可以观察您在决策端是否存在有偏向的情况，如不存在则这个算法有效性受限，您可以尝试根据分类相应图最高值来计算融合比例。

您好，这训练阶段，我看model_builder.py的 里面的forward 是有TIR数据的，以及对RGB TIR分别计算了损失函数然后相加。
这两天试了很多组合方法，效果都不如直接跟踪RGB单路的效果。
有个困惑，比如我用RGB-T两路的分类响应图（大于0的部分）的均值作为加权的系数（mean_rgb,  mean_ir）， 
```
rate_rgb = mean_rgb / （mean_rgb + mean_ir）
rate_ir = mean_ir / （mean_rgb + mean_ir）
cls = cls_rgb * rate_rgb  + cls_ir * rate_ir

loc = 0.5 * loc_rgb + 0.5 * loc_ir   （AUC为 26.84）
或者 loc = cls_rgb * loc_rgb + cls_ir * loc_ir   (AUC为 43.94)
```
想请问下，这loc处的系数该怎么给呢？  这一点不太明白。 比如对于同一帧, RGB可以得到正确的loc，但TIR没有得到正确的loc，然后直接`loc = 0.5 * loc_rgb + 0.5 * loc_ir`， 这不就影响到了最终的结果嘛。所以我认为当RGB-T两路都可以正确得到loc时，可以这样加，但有一路出现问题，就会影响最后的结果。但您的方法确实比我目前有的方法出色，所以我很困惑。
实在不好意思，又打扰您了， 因为我用DFAT的test_vot.py 测试了您的效果，vot_RGBT数据集的AUC可以得到66.96，我的单路RGB才49.08，同时我觉得我可以通过响应图进行RGB-T融合来提高性能，但我并没有达到目的。

**Comment by Zhangyong-Tang** [comment]
您好，您关于loc的理解是正确的，但是跟踪测试是在一个集合上进行的，我们无法观测每一个样本的具体情况，仅能找到一个较好的全局解。关于您对forward里有tir数据这个疑问，可能是因为再变量取名的时候表示需要，但是明确的是dfat未在rgbt数据上训练（也可能是训练特征级的一个对比实验残留）；关于您第二个问题，您说单路rgb结果为49.08，有点过低，需要确认是否代码实施有问题；关于您的融合策略，目前来看有一点奇怪，直观上感觉是有一些操作对象与您的目标对象不一致。

**Comment by NewboySoCool** [comment]
> 您好，您关于loc的理解是正确的，但是跟踪测试是在一个集合上进行的，我们无法观测每一个样本的具体情况，仅能找到一个较好的全局解。关于您对forward里有tir数据这个疑问，可能是因为再变量取名的时候表示需要，但是明确的是dfat未在rgbt数据上训练（也可能是训练特征级的一个对比实验残留）；关于您第二个问题，您说单路rgb结果为49.08，有点过低，需要确认是否代码实施有问题；关于您的融合策略，目前来看有一点奇怪，直观上感觉是有一些操作对象与您的目标对象不一致。

感谢回复！ 既然训练方法是跟RGB单路训练是一样的，那近日我在查找下原因，感觉是分类头和回归头出现了问题。

**Comment by NewboySoCool** [comment]
> 您好，您关于loc的理解是正确的，但是跟踪测试是在一个集合上进行的，我们无法观测每一个样本的具体情况，仅能找到一个较好的全局解。关于您对forward里有tir数据这个疑问，可能是因为再变量取名的时候表示需要，但是明确的是dfat未在rgbt数据上训练（也可能是训练特征级的一个对比实验残留）；关于您第二个问题，您说单路rgb结果为49.08，有点过低，需要确认是否代码实施有问题；关于您的融合策略，目前来看有一点奇怪，直观上感觉是有一些操作对象与您的目标对象不一致。

感谢您的提醒！ 我先把单路的都测试了一遍，跟踪实施时没有错。然后去看融合策略时的两路跟踪，发现我的后处理中_rescale_bbox()函数第一次在调用RGB单路时把融合后得到的框给修改了，导致在TIR路跟踪时出现错误。 之前RGB单路是AUC_48.21，目前我使用您的方法之后，提升到了AUC_55.89 。 感谢帮助，我会继续尝试其他新的方法计算权重。
